import { 
  Product, 
  Category, 
  User, 
  Address, 
  Order, 
  SellerSupplier, 
  RewardPoint, 
  Invoice 
} from '@/types';

export const MOCK_USERS: User[] = [
  {
    id: 'user-cust-1',
    full_name: 'Bhaskar Jyoti Das',
    email: 'bhaskar.das@example.com',
    phone: '9864012345',
    role: 'customer',
    is_active: true,
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'user-cust-2',
    full_name: 'Ananya Goswami',
    email: 'ananya.g@gmail.com',
    phone: '9864123890',
    role: 'customer',
    is_active: true,
    created_at: '2026-09-12T14:20:00Z',
  },
  {
    id: 'user-cust-3',
    full_name: 'Debojit Sarma',
    email: 'debojit.sarma@outlook.com',
    phone: '9864077654',
    role: 'customer',
    is_active: true,
    created_at: '2026-09-18T09:15:00Z',
  },
  {
    id: 'user-cust-4',
    full_name: 'Rupjyoti Hazarika',
    email: 'rupjyoti.h@gmail.com',
    phone: '9864022334',
    role: 'customer',
    is_active: true,
    created_at: '2026-09-20T11:45:00Z',
  },
  {
    id: 'user-subadmin-1',
    full_name: 'Pranab Saikia',
    email: 'pranab.ops@ncelectro.in',
    phone: '9864098765',
    role: 'sub_admin',
    is_active: true,
    created_at: '2026-08-15T09:00:00Z',
  },
  {
    id: 'user-admin-1',
    full_name: 'Nitul Choudhury (Founder)',
    email: 'admin@ncelectro.in',
    phone: '9864000001',
    role: 'super_admin',
    is_active: true,
    created_at: '2026-08-01T08:00:00Z',
  },
];

export const MOCK_CATEGORIES: Category[] = [
  {
    id: 'cat-cctv',
    name: 'CCTV & Security',
    slug: 'cctv',
    description: 'High-definition surveillance cameras, network video recorders, and smart security sensors for home and commercial properties.',
    image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    sort_order: 1,
    is_active: true,
    product_count: 14,
    sub_categories: [
      {
        id: 'sub-cctv-bullet',
        parent_category_id: 'cat-cctv',
        name: 'Bullet Cameras',
        slug: 'bullet-cameras',
        description: 'Weatherproof long-range outdoor security cameras.',
        sort_order: 1,
        is_active: true,
      },
      {
        id: 'sub-cctv-dome',
        parent_category_id: 'cat-cctv',
        name: 'Dome & Smart Cameras',
        slug: 'dome-cameras',
        description: 'Discreet indoor and outdoor 360-degree security cameras.',
        sort_order: 2,
        is_active: true,
      },
      {
        id: 'sub-cctv-dvr',
        parent_category_id: 'cat-cctv',
        name: 'DVR & NVR Kits',
        slug: 'dvr-nvr-kits',
        description: 'Multi-channel recording kits with local hard drive storage.',
        sort_order: 3,
        is_active: true,
      }
    ]
  },
  {
    id: 'cat-inverters',
    name: 'Inverters & UPS',
    slug: 'inverters',
    description: 'Heavy-duty pure sine wave inverters engineered to withstand voltage fluctuations and deliver silent, reliable power.',
    image_url: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
    sort_order: 2,
    is_active: true,
    product_count: 10,
    sub_categories: [
      {
        id: 'sub-inv-sinewave',
        parent_category_id: 'cat-inverters',
        name: 'Pure Sine Wave Inverters',
        slug: 'pure-sine-wave',
        description: 'Safe for sensitive home electronics, LED TVs, and appliances.',
        sort_order: 1,
        is_active: true,
      },
      {
        id: 'sub-inv-commercial',
        parent_category_id: 'cat-inverters',
        name: 'Commercial & High Capacity',
        slug: 'commercial-high-capacity',
        description: 'High capacity systems for offices, clinics, and shops.',
        sort_order: 2,
        is_active: true,
      }
    ]
  },
  {
    id: 'cat-batteries',
    name: 'Batteries',
    slug: 'batteries',
    description: 'Ultra-durable tall tubular inverter batteries with deep discharge technology and extended warranties for Assam conditions.',
    image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80',
    sort_order: 3,
    is_active: true,
    product_count: 8,
    sub_categories: [
      {
        id: 'sub-bat-tubular',
        parent_category_id: 'cat-batteries',
        name: 'Tall Tubular Batteries',
        slug: 'tall-tubular',
        description: 'Long life cycle and low water loss batteries.',
        sort_order: 1,
        is_active: true,
      },
      {
        id: 'sub-bat-short',
        parent_category_id: 'cat-batteries',
        name: 'Short Tubular & Flat Plate',
        slug: 'short-tubular',
        description: 'Compact energy storage for tight domestic spaces.',
        sort_order: 2,
        is_active: true,
      }
    ]
  },
  {
    id: 'cat-electrical',
    name: 'Electrical & Wiring',
    slug: 'electrical-materials',
    description: 'Certified flame-retardant copper wires, modular switchgears, distribution boards, and circuit protection for residential safety.',
    image_url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    sort_order: 4,
    is_active: true,
    product_count: 18,
    sub_categories: [
      {
        id: 'sub-elec-wires',
        parent_category_id: 'cat-electrical',
        name: 'Cables & House Wires',
        slug: 'cables-house-wires',
        description: 'ISI-marked FRLS fire-retardant wiring.',
        sort_order: 1,
        is_active: true,
      },
      {
        id: 'sub-elec-mcb',
        parent_category_id: 'cat-electrical',
        name: 'MCBs & Protection',
        slug: 'mcb-protection',
        description: 'Miniature circuit breakers and isolators.',
        sort_order: 2,
        is_active: true,
      },
      {
        id: 'sub-elec-switches',
        parent_category_id: 'cat-electrical',
        name: 'Modular Switches & Plates',
        slug: 'modular-switches',
        description: 'Sleek designer plates and shockproof rocker switches.',
        sort_order: 3,
        is_active: true,
      }
    ]
  },
  {
    id: 'cat-accessories',
    name: 'Accessories & Spares',
    slug: 'accessories',
    description: 'Heavy duty inverter trolleys, CCTV SMPS power units, connectors, HDMI cables, and mounting brackets.',
    image_url: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80',
    sort_order: 5,
    is_active: true,
    product_count: 12,
    sub_categories: [
      {
        id: 'sub-acc-cctv',
        parent_category_id: 'cat-accessories',
        name: 'CCTV Power & Connectors',
        slug: 'cctv-power-connectors',
        description: 'SMPS, DC pins, BNC connectors, and brackets.',
        sort_order: 1,
        is_active: true,
      },
      {
        id: 'sub-acc-trolley',
        parent_category_id: 'cat-accessories',
        name: 'Inverter Trolleys',
        slug: 'inverter-trolleys',
        description: 'Sturdy multi-wheel stands for inverter and battery combo.',
        sort_order: 2,
        is_active: true,
      }
    ]
  }
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-cctv-hik-2mp',
    name: 'Hikvision 2MP Smart Hybrid Light Bullet Camera',
    slug: 'hikvision-2mp-smart-hybrid-light-bullet-camera',
    sku: 'HIK-DS-2CE16D0T-LPFS',
    brand: 'Hikvision',
    description: 'High quality imaging with 2 MP, 1920 × 1080 resolution. Smart-Hybrid light optimizes your security with versatile lighting options: full color night vision up to 20m, IR night vision up to 20m. Water and dust resistant (IP67) designed specifically for humid and heavy monsoon weather in Assam. Built-in microphone for real-time audio security.',
    short_description: '2MP Full HD | 20m Color Night Vision | Built-in Audio Mic | IP67 Weatherproof',
    price: 1850,
    original_price: 2450,
    discount_percentage: 24,
    stock_quantity: 42,
    low_stock_threshold: 10,
    reserved_quantity: 2,
    availability: 'in_stock',
    category: {
      id: 'cat-cctv',
      name: 'CCTV & Security',
      slug: 'cctv',
    },
    sub_category: {
      id: 'sub-cctv-bullet',
      name: 'Bullet Cameras',
      slug: 'bullet-cameras',
    },
    primary_image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-1',
        url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Hikvision 2MP Bullet Camera Front'
      },
      {
        id: 'img-2',
        url: 'https://images.unsplash.com/photo-1582139329536-e7284fece509?auto=format&fit=crop&w=800&q=80',
        is_primary: false,
        sort_order: 2,
        alt_text: 'Camera Night Vision Sensor Detail'
      },
      {
        id: 'img-3',
        url: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?auto=format&fit=crop&w=800&q=80',
        is_primary: false,
        sort_order: 3,
        alt_text: 'Mounting Bracket and Weather Seal'
      }
    ],
    specifications: [
      { key: 'Resolution', value: '1920 × 1080 (1080p Full HD)', group: 'Camera Specs' },
      { key: 'Sensor', value: '2.0 megapixel progressive scan CMOS', group: 'Camera Specs' },
      { key: 'Night Vision', value: 'Color night vision up to 20m + IR 20m', group: 'Optical' },
      { key: 'Audio', value: 'Built-in Mic over coaxial cable', group: 'Audio' },
      { key: 'Protection', value: 'IP67 Weatherproof (Outdoor Rated)', group: 'Durability' },
      { key: 'Warranty', value: '2 Years Manufacturer Warranty', group: 'Warranty' },
    ],
    is_active: true,
    is_featured: true,
    has_installation_support: true,
    delivery_time_text: 'Fast Delivery in Guwahati (Same-Day / Next-Day)',
    created_at: '2026-09-01T12:00:00Z',
  },
  {
    id: 'prod-cctv-cp-4mp',
    name: 'CP Plus 4MP Ultra Guard Dome Smart Camera',
    slug: 'cp-plus-4mp-ultra-guard-dome-smart-camera',
    sku: 'CP-VAC-D24L2',
    brand: 'CP PLUS',
    description: 'Crystal clear 4 Megapixel resolution with high-power infrared LEDs for superior night vision. Vandal-proof dome casing ideal for apartment entrances, retail shops, and offices across Guwahati. Includes digital noise reduction and smart motion detection alerts.',
    short_description: '4MP Ultra HD | 30m IR Range | Vandal Resistant Dome | DWDR Clarity',
    price: 2399,
    original_price: 3200,
    discount_percentage: 25,
    stock_quantity: 28,
    low_stock_threshold: 8,
    reserved_quantity: 1,
    availability: 'in_stock',
    category: {
      id: 'cat-cctv',
      name: 'CCTV & Security',
      slug: 'cctv',
    },
    sub_category: {
      id: 'sub-cctv-dome',
      name: 'Dome & Smart Cameras',
      slug: 'dome-cameras',
    },
    primary_image: 'https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-cp1',
        url: 'https://images.unsplash.com/photo-1549144511-f099e773c147?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'CP Plus 4MP Dome Camera'
      }
    ],
    specifications: [
      { key: 'Image Sensor', value: '4MP HQ IS Image Sensor', group: 'Sensor' },
      { key: 'Lens', value: '3.6mm Fixed Focal Lens', group: 'Optical' },
      { key: 'IR Range', value: '30 Meters with Smart IR', group: 'Night Vision' },
      { key: 'Housing', value: 'High Impact Polycarbonate Dome', group: 'Build' },
      { key: 'Warranty', value: '2 Years Comprehensive Warranty', group: 'Warranty' },
    ],
    is_active: true,
    is_featured: true,
    has_installation_support: true,
    delivery_time_text: 'Same-Day Dispatch in Guwahati',
    created_at: '2026-09-02T10:00:00Z',
  },
  {
    id: 'prod-inv-luminous-zelio',
    name: 'Luminous Zelio+ 1100 Pure Sine Wave Inverter',
    slug: 'luminous-zelio-plus-1100-pure-sine-wave-inverter',
    sku: 'LUM-ZELIO-1100',
    brand: 'Luminous',
    description: 'India most trusted smart home inverter with an intelligent 32-bit DSP processor. Features an intuitive LED display indicating battery charging time & backup time in hours and minutes. Safe for all sensitive gadgets, computers, and medical equipment. Hassle-free automatic bypass switch.',
    short_description: '900VA / 12V Pure Sine Wave | Smart LCD Display | MCB Protection | Silent Operation',
    price: 7499,
    original_price: 9200,
    discount_percentage: 18,
    stock_quantity: 19,
    low_stock_threshold: 5,
    reserved_quantity: 0,
    availability: 'in_stock',
    category: {
      id: 'cat-inverters',
      name: 'Inverters & UPS',
      slug: 'inverters',
    },
    sub_category: {
      id: 'sub-inv-sinewave',
      name: 'Pure Sine Wave Inverters',
      slug: 'pure-sine-wave',
    },
    primary_image: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-lum1',
        url: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Luminous Zelio 1100 Inverter Front Display'
      }
    ],
    specifications: [
      { key: 'Capacity', value: '900 VA / Rated Power 756 W', group: 'Power' },
      { key: 'Voltage', value: '12V Single Battery System', group: 'System' },
      { key: 'Technology', value: 'DSP Controlled Pure Sine Wave', group: 'Technology' },
      { key: 'Display', value: 'Smart LCD Display (Hours & Mins Remaining)', group: 'Features' },
      { key: 'Warranty', value: '24 Months On-site Guwahati Support', group: 'Warranty' },
    ],
    is_active: true,
    is_featured: true,
    has_installation_support: true,
    delivery_time_text: 'Delivery & Setup Support Available in Guwahati',
    created_at: '2026-09-03T11:00:00Z',
  },
  {
    id: 'prod-bat-luminous-150ah',
    name: 'Luminous Red Charge RC 18000 150Ah Tall Tubular Battery',
    slug: 'luminous-red-charge-150ah-tall-tubular-battery',
    sku: 'LUM-RC-18000-150',
    brand: 'Luminous',
    description: 'Specially engineered high performance tall tubular battery with patented alloy composition for rugged power backup needs in Guwahati. Fast recovery from deep discharge, ultra-low maintenance with level indicators, and 99.99% pure lead plates.',
    short_description: '150Ah Capacity | Tall Tubular Design | 36 Months Warranty (18F + 18P)',
    price: 13999,
    original_price: 17200,
    discount_percentage: 19,
    stock_quantity: 14,
    low_stock_threshold: 4,
    reserved_quantity: 1,
    availability: 'in_stock',
    category: {
      id: 'cat-batteries',
      name: 'Batteries',
      slug: 'batteries',
    },
    sub_category: {
      id: 'sub-bat-tubular',
      name: 'Tall Tubular Batteries',
      slug: 'tall-tubular',
    },
    primary_image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-bat1',
        url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Luminous Red Charge Battery 150Ah'
      }
    ],
    specifications: [
      { key: 'Nominal Capacity', value: '150 Ah @ C20', group: 'Capacity' },
      { key: 'Design', value: 'Tall Tubular (Spine Grid Construction)', group: 'Design' },
      { key: 'Electrolyte Volume', value: 'High Acid Volume per Ampere Hour', group: 'Specs' },
      { key: 'Warranty', value: '36 Months (18 Months Replacement + 18 Pro-rata)', group: 'Warranty' },
    ],
    is_active: true,
    is_featured: true,
    has_installation_support: true,
    delivery_time_text: 'Heavy item delivered directly to doorstep + battery setup',
    created_at: '2026-09-04T08:00:00Z',
  },
  {
    id: 'prod-elec-havells-wire',
    name: 'Havells Life Line Plus S3 2.5 sq mm Single Core HRFR Wire (90m)',
    slug: 'havells-lifeline-plus-2-5-sq-mm-wire-90m',
    sku: 'HAV-LLP-250-90M',
    brand: 'Havells',
    description: '100% electrolytic grade annealed bare copper wire with heat-resistant flame retardant (HRFR) PVC insulation. Engineered for utmost fire protection with 101% conductivity to minimize electricity leakage and power bills.',
    short_description: '2.5 sq mm | 90 Meters Coil | 100% Bare Copper | Fire Retardant HRFR',
    price: 3450,
    original_price: 4300,
    discount_percentage: 20,
    stock_quantity: 65,
    low_stock_threshold: 15,
    reserved_quantity: 0,
    availability: 'in_stock',
    category: {
      id: 'cat-electrical',
      name: 'Electrical & Wiring',
      slug: 'electrical-materials',
    },
    sub_category: {
      id: 'sub-elec-wires',
      name: 'Cables & House Wires',
      slug: 'cables-house-wires',
    },
    primary_image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-wire1',
        url: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Havells Lifeline Plus Wire Coil'
      }
    ],
    specifications: [
      { key: 'Conductor Size', value: '2.5 sq. mm Single Core', group: 'Conductor' },
      { key: 'Insulation', value: 'HRFR (Heat Resistant Flame Retardant)', group: 'Safety' },
      { key: 'Length', value: '90 Meters Standard Coil', group: 'Dimensions' },
      { key: 'Standard', value: 'IS 694 Certified', group: 'Compliance' },
    ],
    is_active: true,
    is_featured: false,
    has_installation_support: false,
    delivery_time_text: 'Fast Delivery in Guwahati',
    created_at: '2026-09-05T09:00:00Z',
  },
  {
    id: 'prod-elec-schneider-mcb',
    name: 'Schneider Electric Acti9 32A Double Pole MCB C-Curve',
    slug: 'schneider-electric-acti9-32a-double-pole-mcb',
    sku: 'SCH-A9-DP-32A',
    brand: 'Schneider Electric',
    description: 'Premium dual-pole miniature circuit breaker with VisiSafe and VisiTrip indicators for instantaneous fault identification. Ensures reliable overload and short circuit isolation for main residential power panels.',
    short_description: '32A Double Pole | 10kA Breaking Capacity | C-Curve Trip | VisiTrip Tech',
    price: 940,
    original_price: 1250,
    discount_percentage: 25,
    stock_quantity: 35,
    low_stock_threshold: 10,
    reserved_quantity: 0,
    availability: 'in_stock',
    category: {
      id: 'cat-electrical',
      name: 'Electrical & Wiring',
      slug: 'electrical-materials',
    },
    sub_category: {
      id: 'sub-elec-mcb',
      name: 'MCBs & Protection',
      slug: 'mcb-protection',
    },
    primary_image: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-mcb1',
        url: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Schneider MCB 32A Double Pole'
      }
    ],
    specifications: [
      { key: 'Current Rating', value: '32 Amperes (Double Pole)', group: 'Electrical' },
      { key: 'Breaking Capacity', value: '10kA as per IEC 60898-1', group: 'Capacity' },
      { key: 'Trip Curve', value: 'C-Curve (Magnetic operation 5-10 In)', group: 'Trip' },
    ],
    is_active: true,
    is_featured: false,
    has_installation_support: true,
    delivery_time_text: 'Same-day delivery across Guwahati',
    created_at: '2026-09-06T14:00:00Z',
  },
  {
    id: 'prod-acc-trolley-hd',
    name: 'NC Electro Premium Inverter & Battery Stacking Trolley',
    slug: 'nc-electro-premium-inverter-battery-trolley',
    sku: 'NC-TR-HEAVY-01',
    brand: 'NC Electro Pro',
    description: 'Heavy gauge unbreakable ABS modular trolley designed to house single or double tall tubular batteries underneath with the inverter securely mounted on top. 5 heavy-duty castors for effortless gliding and floor protection.',
    short_description: 'Reinforced Structure | Multi-wheel Gliders | Spill-proof Acid Trap Basin',
    price: 1450,
    original_price: 1999,
    discount_percentage: 27,
    stock_quantity: 22,
    low_stock_threshold: 6,
    reserved_quantity: 0,
    availability: 'in_stock',
    category: {
      id: 'cat-accessories',
      name: 'Accessories & Spares',
      slug: 'accessories',
    },
    sub_category: {
      id: 'sub-acc-trolley',
      name: 'Inverter Trolleys',
      slug: 'inverter-trolleys',
    },
    primary_image: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-tr1',
        url: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Heavy duty trolley'
      }
    ],
    specifications: [
      { key: 'Material', value: 'High Density Virgin Polypropylene', group: 'Build' },
      { key: 'Load Capacity', value: 'Up to 90 KG weight rating', group: 'Durability' },
      { key: 'Wheels', value: '5 Swivel Castors (2 with locks)', group: 'Mobility' },
    ],
    is_active: true,
    is_featured: false,
    has_installation_support: false,
    delivery_time_text: 'Delivered assembled',
    created_at: '2026-09-07T10:00:00Z',
  },
  {
    id: 'prod-cctv-kit-dahua-4ch',
    name: 'Dahua 4-Channel 1080p Smart DVR Surveillance Kit with 1TB HDD',
    slug: 'dahua-4-channel-1080p-smart-dvr-surveillance-kit',
    sku: 'DAH-KIT-4CH-1TB',
    brand: 'Dahua',
    description: 'Complete all-in-one surveillance setup: includes 1x 4-Channel XVR recorder, 2x 2MP outdoor bullet cameras, 2x 2MP indoor dome cameras, 1TB Seagate surveillance hard drive, 4-channel SMPS power supply, and 60m 3+1 CCTV wire roll.',
    short_description: 'Complete 4-Cam Kit | 1TB HDD Included | Remote Mobile App View | Full Cables & SMPS',
    price: 11499,
    original_price: 15500,
    discount_percentage: 26,
    stock_quantity: 8,
    low_stock_threshold: 3,
    reserved_quantity: 1,
    availability: 'in_stock',
    category: {
      id: 'cat-cctv',
      name: 'CCTV & Security',
      slug: 'cctv',
    },
    sub_category: {
      id: 'sub-cctv-dvr',
      name: 'DVR & NVR Kits',
      slug: 'dvr-nvr-kits',
    },
    primary_image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
    images: [
      {
        id: 'img-dvr1',
        url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
        is_primary: true,
        sort_order: 1,
        alt_text: 'Dahua 4-Channel DVR Security Kit'
      }
    ],
    specifications: [
      { key: 'Channels', value: '4 Channels HD-CVI/AHD/TVI/CVBS/IP', group: 'Recorder' },
      { key: 'Storage', value: '1TB Surveillance Hard Drive Pre-installed', group: 'Storage' },
      { key: 'Cameras Included', value: '2x Bullet Outdoor + 2x Dome Indoor', group: 'Kit Contents' },
      { key: 'Remote Access', value: 'DMSS iOS / Android Mobile App Live Streaming', group: 'Connectivity' },
      { key: 'Installation Support', value: 'Professional technician installation available in Guwahati', group: 'Service' },
    ],
    is_active: true,
    is_featured: true,
    has_installation_support: true,
    delivery_time_text: 'Guwahati Delivery + Professional On-site Setup',
    created_at: '2026-09-08T15:00:00Z',
  }
];

export const MOCK_ADDRESSES: Address[] = [
  {
    id: 'addr-1',
    user_id: 'user-cust-1',
    label: 'Home',
    recipient_name: 'Bhaskar Jyoti Das',
    phone: '9864012345',
    address_line1: 'House No. 42, Zoo Road Tiniali, Near Shraddhanjali Kanan',
    address_line2: 'Sundarpur',
    city: 'Guwahati',
    state: 'Assam',
    pincode: '781005',
    is_default: true,
  },
  {
    id: 'addr-2',
    user_id: 'user-cust-1',
    label: 'Office / Clinic',
    recipient_name: 'Bhaskar Das',
    phone: '9864012345',
    address_line1: 'Ground Floor, Commercial Complex, GS Road',
    address_line2: 'Christian Basti',
    city: 'Guwahati',
    state: 'Assam',
    pincode: '781005',
    is_default: false,
  }
];

export const MOCK_SELLER_SUPPLIERS: SellerSupplier[] = [
  {
    id: 'sup-1',
    business_name: 'Brahmaputra Electrical & Industrial Supplies',
    contact_person: 'Gautam Kalita',
    phone: '9864055221',
    email: 'brahmaputra.supplies@gmail.com',
    city: 'Guwahati',
    pincode: '781001',
    is_active: true,
    notes: 'Primary supplier for Havells wires and Schneider MCBs near Paltan Bazar.',
    supported_categories: ['Electrical & Wiring', 'Accessories & Spares'],
    created_at: '2026-08-10T10:00:00Z',
  },
  {
    id: 'sup-2',
    business_name: 'Assam Electro & Power Hub',
    contact_person: 'Ramesh Sharma',
    phone: '9864033445',
    email: 'assamelectrohub@rediffmail.com',
    city: 'Guwahati',
    pincode: '781005',
    is_active: true,
    notes: 'Authorized wholesale stockist for Luminous inverters & tubular batteries in Ganeshguri.',
    supported_categories: ['Inverters & UPS', 'Batteries'],
    created_at: '2026-08-12T11:00:00Z',
  },
  {
    id: 'sup-3',
    business_name: 'Kamakhya Surveillance & Security Systems',
    contact_person: 'Bikram Singha',
    phone: '9864077889',
    email: 'kamakhyacctv@outlook.com',
    city: 'Guwahati',
    pincode: '781024',
    is_active: true,
    notes: 'Master distributor for Hikvision, CP Plus, and Dahua cameras in Beltola.',
    supported_categories: ['CCTV & Security', 'Accessories & Spares'],
    created_at: '2026-08-15T14:00:00Z',
  },
  {
    id: 'sup-4',
    business_name: 'Pragjyotish Power Solutions',
    contact_person: 'Mridul Bora',
    phone: '9864044112',
    email: 'pragpower@gmail.com',
    city: 'Guwahati',
    pincode: '781036',
    is_active: true,
    notes: 'Fast delivery supplier for Jalukbari & Maligaon corridor.',
    supported_categories: ['Inverters & UPS', 'Batteries', 'Electrical & Wiring'],
    created_at: '2026-08-18T16:00:00Z',
  }
];

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'NC-2026-1001',
    user_id: 'user-cust-1',
    customer_name: 'Bhaskar Jyoti Das',
    customer_email: 'bhaskar.das@example.com',
    customer_phone: '9864012345',
    status: 'out_for_delivery',
    address: MOCK_ADDRESSES[0],
    items: [
      {
        id: 'item-101',
        product_id: 'prod-cctv-hik-2mp',
        product_name: 'Hikvision 2MP Smart Hybrid Light Bullet Camera',
        sku: 'HIK-DS-2CE16D0T-LPFS',
        brand: 'Hikvision',
        price: 1850,
        quantity: 2,
        line_total: 3700,
        image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'item-102',
        product_id: 'prod-inv-luminous-zelio',
        product_name: 'Luminous Zelio+ 1100 Pure Sine Wave Inverter',
        sku: 'LUM-ZELIO-1100',
        brand: 'Luminous',
        price: 7499,
        quantity: 1,
        line_total: 7499,
        image_url: 'https://images.unsplash.com/photo-1544724569-5f546fd6f2b5?auto=format&fit=crop&w=800&q=80',
      }
    ],
    subtotal: 11199,
    discount: 500,
    shipping: 0,
    tax: 1925,
    total: 12624,
    accepted_by_id: 'user-subadmin-1',
    accepted_by_name: 'Pranab Saikia',
    accepted_at: '2026-09-28T08:30:00Z',
    seller_supplier_id: 'sup-2',
    seller_supplier_name: 'Assam Electro & Power Hub (Ganeshguri)',
    seller_supplier_pincode: '781005',
    customer_note: 'Please test the inverter display upon delivery. Thanks.',
    created_at: '2026-09-28T08:15:00Z',
    updated_at: '2026-09-28T11:45:00Z',
    status_history: [
      {
        id: 'hist-1',
        from_status: null,
        to_status: 'order_placed',
        changed_by_name: 'Bhaskar Jyoti Das',
        note: 'Order placed via customer web portal',
        created_at: '2026-09-28T08:15:00Z',
      },
      {
        id: 'hist-2',
        from_status: 'order_placed',
        to_status: 'accepted',
        changed_by_name: 'Pranab Saikia (Sub-Admin)',
        note: 'Order accepted by Guwahati operations coordinator',
        created_at: '2026-09-28T08:30:00Z',
      },
      {
        id: 'hist-3',
        from_status: 'accepted',
        to_status: 'processing',
        changed_by_name: 'Pranab Saikia',
        note: 'Stock allocated at Ganeshguri Hub, assigned technician for camera testing',
        created_at: '2026-09-28T09:10:00Z',
      },
      {
        id: 'hist-4',
        from_status: 'processing',
        to_status: 'ready_for_dispatch',
        changed_by_name: 'Pranab Saikia',
        note: 'Inverter packed with warranty cards, QC approved',
        created_at: '2026-09-28T10:30:00Z',
      },
      {
        id: 'hist-5',
        from_status: 'ready_for_dispatch',
        to_status: 'shipped',
        changed_by_name: 'Pranab Saikia',
        note: 'Handed over to local Guwahati delivery van (Van #AS-01-ET-4492)',
        created_at: '2026-09-28T11:00:00Z',
      },
      {
        id: 'hist-6',
        from_status: 'shipped',
        to_status: 'out_for_delivery',
        changed_by_name: 'Pranab Saikia',
        note: 'Delivery executive reached Zoo Road area, coordinating with customer',
        created_at: '2026-09-28T11:45:00Z',
      }
    ]
  },
  {
    id: 'ord-1002',
    order_number: 'NC-2026-1002',
    user_id: 'user-cust-2',
    customer_name: 'Ananya Goswami',
    customer_email: 'ananya.g@gmail.com',
    customer_phone: '9864123890',
    status: 'order_placed',
    address: {
      id: 'addr-cust-2',
      user_id: 'user-cust-2',
      label: 'Home',
      recipient_name: 'Ananya Goswami',
      phone: '9864123890',
      address_line1: 'B Baruah Road, Near Nehru Stadium',
      city: 'Guwahati',
      state: 'Assam',
      pincode: '781007',
      is_default: true,
    },
    items: [
      {
        id: 'item-201',
        product_id: 'prod-cctv-kit-dahua-4ch',
        product_name: 'Dahua 4-Channel 1080p Smart DVR Surveillance Kit with 1TB HDD',
        sku: 'DAH-KIT-4CH-1TB',
        brand: 'Dahua',
        price: 11499,
        quantity: 1,
        line_total: 11499,
        image_url: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?auto=format&fit=crop&w=800&q=80',
      }
    ],
    subtotal: 11499,
    discount: 0,
    shipping: 0,
    tax: 2069,
    total: 13568,
    accepted_by_id: null,
    accepted_by_name: null,
    accepted_at: null,
    seller_supplier_id: null,
    seller_supplier_name: null,
    customer_note: 'Requesting installation today if possible before 6 PM.',
    created_at: '2026-09-28T12:05:00Z',
    updated_at: '2026-09-28T12:05:00Z',
    status_history: [
      {
        id: 'hist-201',
        from_status: null,
        to_status: 'order_placed',
        changed_by_name: 'Ananya Goswami',
        note: 'Order placed via online catalog. Awaiting Sub-Admin acceptance.',
        created_at: '2026-09-28T12:05:00Z',
      }
    ]
  },
  {
    id: 'ord-1003',
    order_number: 'NC-2026-1003',
    user_id: 'user-cust-1',
    customer_name: 'Bhaskar Jyoti Das',
    customer_email: 'bhaskar.das@example.com',
    customer_phone: '9864012345',
    status: 'delivered',
    address: MOCK_ADDRESSES[0],
    items: [
      {
        id: 'item-301',
        product_id: 'prod-bat-luminous-150ah',
        product_name: 'Luminous Red Charge RC 18000 150Ah Tall Tubular Battery',
        sku: 'LUM-RC-18000-150',
        brand: 'Luminous',
        price: 13999,
        quantity: 1,
        line_total: 13999,
        image_url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=800&q=80',
      },
      {
        id: 'item-302',
        product_id: 'prod-acc-trolley-hd',
        product_name: 'NC Electro Premium Inverter & Battery Stacking Trolley',
        sku: 'NC-TR-HEAVY-01',
        brand: 'NC Electro Pro',
        price: 1450,
        quantity: 1,
        line_total: 1450,
        image_url: 'https://images.unsplash.com/photo-1588508065123-287b28e013da?auto=format&fit=crop&w=800&q=80',
      }
    ],
    subtotal: 15449,
    discount: 500,
    shipping: 0,
    tax: 2690,
    total: 17639,
    accepted_by_id: 'user-subadmin-1',
    accepted_by_name: 'Pranab Saikia',
    accepted_at: '2026-09-25T09:00:00Z',
    seller_supplier_id: 'sup-2',
    seller_supplier_name: 'Assam Electro & Power Hub (Ganeshguri)',
    seller_supplier_pincode: '781005',
    customer_note: 'Battery installation completed smoothly.',
    created_at: '2026-09-25T08:45:00Z',
    updated_at: '2026-09-25T16:30:00Z',
    status_history: [
      {
        id: 'hist-301',
        from_status: null,
        to_status: 'order_placed',
        changed_by_name: 'Bhaskar Jyoti Das',
        note: 'Order placed',
        created_at: '2026-09-25T08:45:00Z',
      },
      {
        id: 'hist-302',
        from_status: 'order_placed',
        to_status: 'accepted',
        changed_by_name: 'Pranab Saikia',
        note: 'Accepted by Pranab Saikia',
        created_at: '2026-09-25T09:00:00Z',
      },
      {
        id: 'hist-303',
        from_status: 'accepted',
        to_status: 'processing',
        changed_by_name: 'Pranab Saikia',
        note: 'Dispatched to technician for battery testing',
        created_at: '2026-09-25T10:15:00Z',
      },
      {
        id: 'hist-304',
        from_status: 'processing',
        to_status: 'ready_for_dispatch',
        changed_by_name: 'Pranab Saikia',
        note: 'Staged for delivery',
        created_at: '2026-09-25T11:30:00Z',
      },
      {
        id: 'hist-305',
        from_status: 'ready_for_dispatch',
        to_status: 'shipped',
        changed_by_name: 'Pranab Saikia',
        note: 'Out on delivery vehicle',
        created_at: '2026-09-25T12:00:00Z',
      },
      {
        id: 'hist-306',
        from_status: 'shipped',
        to_status: 'out_for_delivery',
        changed_by_name: 'Pranab Saikia',
        note: 'Technician reached customer location',
        created_at: '2026-09-25T15:30:00Z',
      },
      {
        id: 'hist-307',
        from_status: 'out_for_delivery',
        to_status: 'delivered',
        changed_by_name: 'Pranab Saikia',
        note: 'Delivered and battery terminal connection tested. 1 Reward point credited to Pranab Saikia.',
        created_at: '2026-09-25T16:30:00Z',
      }
    ]
  }
];

export const MOCK_INVOICES: Invoice[] = [
  {
    id: 'inv-1001',
    document_number: 'INV-NC-2026-1001',
    order_id: 'ord-1001',
    order_number: 'NC-2026-1001',
    customer_name: 'Bhaskar Jyoti Das',
    total_amount: 12624,
    status: 'generated',
    file_url: '/invoices/INV-NC-2026-1001.pdf',
    created_at: '2026-09-28T08:16:00Z',
  },
  {
    id: 'inv-1003',
    document_number: 'INV-NC-2026-1003',
    order_id: 'ord-1003',
    order_number: 'NC-2026-1003',
    customer_name: 'Bhaskar Jyoti Das',
    total_amount: 17639,
    status: 'generated',
    file_url: '/invoices/INV-NC-2026-1003.pdf',
    created_at: '2026-09-25T08:46:00Z',
  },
  {
    id: 'inv-1002',
    document_number: 'INV-NC-2026-1002',
    order_id: 'ord-1002',
    order_number: 'NC-2026-1002',
    customer_name: 'Ananya Goswami',
    total_amount: 13568,
    status: 'pending',
    created_at: '2026-09-28T12:05:00Z',
  }
];

export const MOCK_REWARD_POINTS: RewardPoint[] = [
  {
    id: 'rew-1',
    user_id: 'user-subadmin-1',
    user_name: 'Pranab Saikia',
    order_id: 'ord-1003',
    order_number: 'NC-2026-1003',
    points: 1,
    reason: 'Order fulfilled at DELIVERED stage',
    created_at: '2026-09-25T16:30:00Z',
  },
  {
    id: 'rew-2',
    user_id: 'user-subadmin-1',
    user_name: 'Pranab Saikia',
    order_id: 'ord-0980',
    order_number: 'NC-2026-0980',
    points: 1,
    reason: 'Order fulfilled at DELIVERED stage',
    created_at: '2026-09-24T14:10:00Z',
  },
  {
    id: 'rew-3',
    user_id: 'user-subadmin-1',
    user_name: 'Pranab Saikia',
    order_id: 'ord-0975',
    order_number: 'NC-2026-0975',
    points: 1,
    reason: 'Order fulfilled at DELIVERED stage',
    created_at: '2026-09-22T17:40:00Z',
  }
];
